### ISSUE TITLE
ecs instance created by customer image(contain data disk)，can not set data disk type 

### ISSUE THREAD

**Issue by mylife6585** [terraform-providers/terraform-provider-alicloud#1595] opened 2019-08-23 08:49 UTC
Hi there,

### Terraform Version

Terraform v0.12.7
+ provider.alicloud v1.55.0

### Affected Resource(s)

alicloud_instance

### Terraform Configuration Files
```hcl
resource "alicloud_instance" "instance_packer_mysql_1" {
  instance_name = "mysql1"
  description   = "mysql1"
  password      = "${var.root_password}"
  tags = {
    app = "mysql"
    env = "test"
  }


  availability_zone    = "${var.availability_zone}"
  instance_charge_type = "PostPaid"
  spot_strategy        = "SpotAsPriceGo"
  instance_type        = "${data.alicloud_instance_types.instance_type_1c1g.instance_types.0.id}"
  image_id             = "m-bp1ewd5q2wfycwaguk87"
  system_disk_category = "cloud_efficiency"
  system_disk_size     = 20

  vswitch_id                 = "${var.souban_sw_f_id}"
  internet_max_bandwidth_out = 0
  security_groups            = "${alicloud_security_group.tmp_default.*.id}"
}
```

OR

```hcl
resource "alicloud_instance" "instance_packer_mysql_1" {
  instance_name = "mysql1"
  description   = "mysql1"
  password      = "${var.root_password}"
  tags = {
    app = "mysql"
    env = "test"
  }


  availability_zone    = "${var.availability_zone}"
  instance_charge_type = "PostPaid"
  spot_strategy        = "SpotAsPriceGo"
  instance_type        = "${data.alicloud_instance_types.instance_type_1c1g.instance_types.0.id}"
  image_id             = "m-bp1ewd5q2wfycwaguk87"
  system_disk_category = "cloud_efficiency"
  system_disk_size     = 20

  vswitch_id                 = "${var.souban_sw_f_id}"
  internet_max_bandwidth_out = 0
  security_groups            = "${alicloud_security_group.tmp_default.*.id}"

  data_disks {
    name                 = "mysql1"
    size                 = "20"
    category             = "cloud_ssd"
    delete_with_instance = true
  }
}
```

### Expected Behavior
data_disk category should be ssd

### Actual Behavior
if I do not set data_disk , instance created by terraform will have two disks,
all  disks's category  is cloud

if I set data_disk, instance created by terraform will have three disks,
one disk's  category  is ssd,other two disks's category is cloud

### Steps to Reproduce
1.  packer create image
```json
{
  "variables": {
    "access_key": "{{env `PACKER_ALICLOUD_ACCESS_KEY`}}",
    "secret_key": "{{env `PACKER_ALICLOUD_SECRET_KEY`}}"
  },
  "builders": [{
    "type": "alicloud-ecs",
    "access_key": "{{user `access_key`}}",
    "secret_key": "{{user `secret_key`}}",
    "region": "cn-hangzhou",
    "image_name": "centos_7_06_64_20G_data_20G_2019072502",
    "source_image": "centos_7_06_64_20G_alibase_20190619.vhd",
    "ssh_username": "root",
    "ssh_password": "password",
    "instance_type": "ecs.t5-lc1m1.small",
    "io_optimized": "true",
    "image_force_delete": "true",
    "system_disk_mapping": {
      "disk_size": 20
    },
    "image_disk_mappings": [{
      "disk_name": "souban",
      "disk_size": 20,
      "disk_category": "cloud_ssd"
    }],
    "vpc_id": "vpc-bp11eexyq6u5p8pjj2izn",
    "vswitch_id": "vsw-bp11m5v0zk4a5ecnqw9j5",
    "ssh_private_ip": "true",
    "tags": {
      "version": "v1.0.0",
      "app": "system-init",
      "date": "2019072501"
    },
  }],
  "provisioners": [{
    "type": "shell",
    "expect_disconnect": "true",
    "inline": [
      "echo xxx",
    ]
  }]
}
```

2. terraform create ecs instance

**Comment by ddaddaddda** [comment] 2019-09-17 10:39
I can't reproduce this issue completely, I think the two disks should be the system disk and the custom image disk. 

1.  When the system disk in the tf config is specified as `system_disk_category`, but disk type is `cloud` has created. This question has not been reproduced. I hope you confirm your configuration.
2. The essence of the image is a snapshot, and the type of the disk is not recorded in the snapshot. Even if the type of the data disk is defined in the json template of the packer, there is still no disk type information in the generated image, and the disk connot have same type with original. 

Currently, the data disk of the images cannot be specified in the terraform config.

**Comment by xiaozhu36** [comment] 2019-10-15 08:47
HI @mylife6585 Is there any questions?

**Comment by xiaozhu36** [comment] 2019-11-01 03:43
Closed by no reply.

**Closed by xiaozhu36** 2019-11-01 03:43 UTC
Labels: ECS

**Comment by Junnplus** [comment] 2020-04-23 12:51
@xiaozhu36 have the same problem, image includes ssd data disk, but new instance include cloud_efficiency data disk.
