### ISSUE TITLE
OSS Bucket Creation: No ACL is specified leading to console errors

### ISSUE THREAD

**Issue by arafato** [terraform-providers/terraform-provider-alicloud#1583] opened 2019-08-21 12:28 UTC
Hi--!

If you create a simple OSS bucket like so 
```
resource "alicloud_oss_bucket" "bucket-new" {
  bucket = "myuniquebucket"
  acl    = "public-read"
}
```

there does not seem to be an ACL attached to it. Trying to access it via console leads to the following error:
`There is no corresponding access rights.` 

In the upper right of the web console, the ACL value is set to `Access Control List (ACL) --`.

**Comment by xiaozhu36** [comment] 2019-08-21 16:22
HI, it seems like your ram account have no right to access the bucket by console. Please check it.

**Comment by arafato** [comment] 2019-08-21 16:52
No, I'm admin with full access. This only happens when creating the bucket with Terraform. You will see that the bucket does not have any ACL specified (which is not a valid state hence the error)

**Comment by Lexsss** [comment] 2019-08-23 07:33
Hi Oliver, have you use the same ram account, or two different account? Because I can't reproduce this error, maybe more information I need.

**Comment by arafato** [comment] 2019-08-23 08:54
It's two different RAM accounts but both have full admin access. This error happens only when accessing the bucket in the web console.

**Comment by Lexsss** [comment] 2019-08-27 02:17
In fact, I tried it several times with several accounts and reproduced the error.

It's looks like your RAM account used in web console has no full access, at least you have insufficient access to the oss bucket you created with another account. Please check it.

**Comment by Lexsss** [comment] 2019-09-04 03:22
Hi Oliver, Is everything going well? If you have any other problem, welcome to feedback here.

**Comment by xiaozhu36** [comment] 2019-09-05 09:28
Closed by no reply

**Closed by xiaozhu36** 2019-09-05 09:28 UTC
Labels: OSS
